### ISSUE TITLE
[question] fixing bugs.

### ISSUE THREAD

**Issue by Smorted** [reiryuki/Miui-Home-Magisk-Module#1]
(Can't uninstall apps and Recents provider can't kill recents apps)

since these are critical issues and are very important in any launcher, i can't use this mod until they get fixed, so my question is when are you going to fix them? or is the fix in progress or impossible due to android 12 related issue?

+ im on android 12 using ancient os 6.2

**Comment by reiryuki** [comment]
I don't know how to fix
I'm sorry
