### ISSUE TITLE
Doesn't work on A14 (v1.13)

### ISSUE THREAD

**Issue by cherlis** [reiryuki/Miui-Home-Magisk-Module#4]
Doesn't work on A14 (v1.13)
Redmi Note 10 Pro device.  Rom Project Matrixx A14

![Screenshot_20240328-120757_QuickSwitch](https://github.com/reiryuki/Miui-Home-Magisk-Module/assets/17528476/62842e16-4224-4877-849a-132663787c99)

**Comment by reiryuki** [comment]
Please read README Optionals!
