### ISSUE TITLE
No android 14 app opening animation with logs

### ISSUE THREAD

**Issue by justas2006** [reiryuki/Miui-Home-Magisk-Module#6]
https://github.com/reiryuki/Miui-Home-Magisk-Module/assets/154797694/552f7922-5bb8-4088-b0ac-86a74657cf02

[magisk_install_log_2024-04-14T10.57.58.log](https://github.com/reiryuki/Miui-Home-Magisk-Module/files/14969965/magisk_install_log_2024-04-14T10.57.58.log)
[logcat_04-14-2024_11-08-23.txt](https://github.com/reiryuki/Miui-Home-Magisk-Module/files/14969966/logcat_04-14-2024_11-08-23.txt)
[z.zip](https://github.com/reiryuki/Miui-Home-Magisk-Module/files/14969967/z.zip)

**Comment by justas2006** [comment]
M
[logcat_04-14-2024_12-10-48.txt](https://github.com/reiryuki/Miui-Home-Magisk-Module/files/14970067/logcat_04-14-2024_12-10-48.txt)
ore logcat

**Comment by reiryuki** [comment]
It's not a bug
That's the default animation of the launcher
I don't know how to change that

**Comment by justas2006** [comment]
> It's not a bug That's the default animation of the launcher I don't know how to change that sorry

This is what it looks like on miui. https://youtu.be/_BUp-v0Oq0Y?t=27. The app opens from the icon, not from the air.

**Comment by reiryuki** [comment]
the app is old version
nothing I can do with that
